### ISSUE TITLE
three_camera_stream.bonsai

### ISSUE THREAD

**Issue by Petrina-Lau** [int-brain-lab/iblscripts#39]
Hi there, I have recently re-downloaded iblscripts and reinstalled bonsai, hoping to find three_cameras_stream.bonsai on the C:\iblscripts\deploy\videopc\bonsai\workflows folder but it is still not there. Could you advise what I can do? 

Cheers,
Petrina

**Comment by nbonacchi** [comment]
Hi @Petrina-Lau the three_camera_streams.bonsai workflow was deprecated in favor of the three_cameras_setup.bonsai workflow, this workflow streams data from all the cameras and also overlays the correct positioning of the mouse holder on the image so users can verify if their cameras are properly positioned on launch of a new session.

**Comment by nbonacchi** [comment]
Answered on Slack closing for now...
