### ISSUE TITLE
User confirms that ephys recording is enabled before starting video recording

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/iblscripts#4]
When running `three_cameras_record.bonsai`, start by asking the user to confirm SpikeGLX recordings are enabled. This prevents that video is started before ephys (causing sync problems).

Related to https://github.com/int-brain-lab/iblrig/issues/223

**Comment by oliche** [comment]
@nbonacchi This is indeed something super important.
If there is a stronger hardware check that could **prevent** the session to run that would be even better. The data may be useless if the order is not respected, so I think the user should not even be able to run a session if video starts prior to ephys.

**Comment by nbonacchi** [comment]
@oliche indeed that would be a useful feature, I would love to figure out a way.
Synchronizing the 3 acquisition computers will require some access to some shared memory of any sort, but most importantly some hook in spikeglx that allows running some code on triggered actions.

@anne-urai As a general rule, the ephys equipment is ALWAYS the first thing one turn on. Usually the rule of thumb is to go from higher recording frequency to lowest so:
ephys 30KHz --> behavior 10KHz --> video 150Hz and lower
